### ISSUE TITLE
.asType(<TYPE>) randomly crashes in concurrent implementation

### ISSUE THREAD

**Issue by johanneshiry** [unitsofmeasurement/uom-se#210] opened 2020-04-21 13:21 UTC
Hi,

after spending days to debug a potential issue I ended up here now. 
I would love to provide some sample code/project but for the moment, I haven't figure out a way to reproduce the issue in stable way as it _seems_ to occur randomly. 

**Following situation:**
We are working in a mixed java/scala codebase that makes use of this quantity implementation incl. several custom implementations of Units. 

We are using several threads/actors (using akka for concurrent operations) that receive data and process data concurrently. In each of these threads/actors, we're doing several operations with quantities incl. multiplication of specific quantities (example below) and casting them afterwards with `asType(<TYPE>)`. 
For some reason, it sometimes (randomly?) happens that when quantity.asType(<TYPE>) is called, it results in a `java.lang.ClassCastException: The unit: S is not compatible with quantities of type interface javax.measure.quantity.ElectricConductance`. It is obvious, that this exception is wrong, because the unit `S` for Siemens is of type `ElectricConductance` (see `tec.uom.se.unit.Units`:250). 

It is important to mention, that this issue is not type dependent. The same happens for e.g. type of `ElectricResistance` (`java.lang.ClassCastException: The unit: Ω is not compatible with quantities of type interface javax.measure.quantity.ElectricResistance`), but it is defined exactly like this @  `tec.uom.se.unit.Units`:243.

After debugging several hours I was able to trace the issue down to the dimension comparison and it turned out that `quantity.getUnit().getDimension()` _seems_ not to be stable returning the same value in the sense that sometimes it returns `ONE` or an incomplete signature of the Dimensions of the type which ends up in the exceptions shown above. 

I searched the issues here and didn't found any solution and all my attempts to solve this issue where failing. Is there any known bug, that prevents our scenario/use case from working? 

**Example:**
[quantityA] = OHM_PER_KILOMETRE
[quantityB] = KILOMETRE 

quantityA.multiply(quantityB).asType(classOf[ElectricResistance]) -> randomly throws exception even if one would expect this to be of type OHM 

My assumption is, that somehow (somewhere?) the way the dimension creation in `getDimension()` is implemented is either not loaded correctly as static class in the java/scala combination or there is an issue with the concurrent access to it. But as written, I couldn't figured it out by myself so far 

As we make extensive use of quantities it would be great if somebody could provide some help on this issue. If you need more information pls let me know. If I can manage to somehow get a project up and running that reproduces this issue I'll provided it asap but atm I didn't got one running. 

**Project Meta:**
- java version: 11 (8 also didn't worked, already tried)
- scala version: 2.13.0 / 2.13.1 
- units of measurement version: 1.0.10
- concurrency framework: akka 
- code language that calls the `getDimension()`part is scala

**Full exceptions:**
```
09:41:34.120 ERROR - The unit: S is not compatible with quantities of type interface javax.measure.quantity.ElectricConductance
 java.lang.ClassCastException: The unit: S is not compatible with quantities of type interface javax.measure.quantity.ElectricConductance
	at tec.uom.se.AbstractUnit.asType(AbstractUnit.java:260) ~[uom-se-1.0.10.jar:?]
	at tec.uom.se.AbstractUnit.asType(AbstractUnit.java:69) ~[uom-se-1.0.10.jar:?]
	at tec.uom.se.AbstractQuantity.asType(AbstractQuantity.java:380) ~[uom-se-1.0.10.jar:?]
	at tec.uom.se.AbstractQuantity.asType(AbstractQuantity.java:110) ~[uom-se-1.0.10.jar:?]
	at edu.ie3.simona.model.grid.LineModel$.buildLineModel(LineModel.scala:143) ~[classes/:?]
	at edu.ie3.simona.model.grid.LineModel$.apply(LineModel.scala:107) ~[classes/:?]
	at edu.ie3.simona.model.grid.GridModel$$anonfun$2.applyOrElse(GridModel.scala:409) ~[classes/:?]
	at edu.ie3.simona.model.grid.GridModel$$anonfun$2.applyOrElse(GridModel.scala:399) ~[classes/:?]
	at scala.collection.Iterator$$anon$7.hasNext(Iterator.scala:496) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.Growable.addAll(Growable.scala:61) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.Growable.addAll$(Growable.scala:59) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.ArrayBuffer.addAll(ArrayBuffer.scala:148) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.ArrayBuffer.addAll(ArrayBuffer.scala:41) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.ArrayBuffer$.from(ArrayBuffer.scala:267) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.ArrayBuffer$.from(ArrayBuffer.scala:255) ~[scala-library-2.13.0.jar:?]
	at scala.collection.IterableOps.collect(Iterable.scala:663) ~[scala-library-2.13.0.jar:?]
	at scala.collection.IterableOps.collect$(Iterable.scala:662) ~[scala-library-2.13.0.jar:?]
	at scala.collection.AbstractIterable.collect(Iterable.scala:904) ~[scala-library-2.13.0.jar:?]
	at edu.ie3.simona.model.grid.GridModel$.buildAndValidate(GridModel.scala:399) ~[classes/:?]
	at edu.ie3.simona.model.grid.GridModel$.apply(GridModel.scala:62) ~[classes/:?]
	at edu.ie3.simona.agent.grid.GridAgent$$anonfun$2.applyOrElse(GridAgent.scala:226) ~[classes/:?]
	at edu.ie3.simona.agent.grid.GridAgent$$anonfun$2.applyOrElse(GridAgent.scala:167) ~[classes/:?]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:37) ~[scala-library-2.13.0.jar:?]
	at akka.actor.FSM.processEvent(FSM.scala:801) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.FSM.processEvent$(FSM.scala:798) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at edu.ie3.simona.agent.grid.GridAgent.akka$actor$LoggingFSM$$super$processEvent(GridAgent.scala:109) ~[classes/:?]
	at akka.actor.LoggingFSM.processEvent(FSM.scala:941) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:923) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at edu.ie3.simona.agent.grid.GridAgent.processEvent(GridAgent.scala:109) ~[classes/:?]
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:795) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:790) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.Actor.aroundReceive(Actor.scala:532) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.Actor.aroundReceive$(Actor.scala:530) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at edu.ie3.simona.agent.grid.GridAgent.aroundReceive(GridAgent.scala:109) ~[classes/:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.ActorCell.invoke(ActorCell.scala:543) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.dispatch.Mailbox.run(Mailbox.scala:230) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
```

```
09:41:34.121 ERROR - The unit: Ω is not compatible with quantities of type interface javax.measure.quantity.ElectricResistance
 java.lang.ClassCastException: The unit: Ω is not compatible with quantities of type interface javax.measure.quantity.ElectricResistance
	at tec.uom.se.AbstractUnit.asType(AbstractUnit.java:260) ~[uom-se-1.0.10.jar:?]
	at tec.uom.se.AbstractUnit.asType(AbstractUnit.java:69) ~[uom-se-1.0.10.jar:?]
	at tec.uom.se.AbstractQuantity.asType(AbstractQuantity.java:380) ~[uom-se-1.0.10.jar:?]
	at tec.uom.se.AbstractQuantity.asType(AbstractQuantity.java:110) ~[uom-se-1.0.10.jar:?]
	at edu.ie3.simona.model.grid.LineModel$.buildLineModel(LineModel.scala:138) ~[classes/:?]
	at edu.ie3.simona.model.grid.LineModel$.apply(LineModel.scala:107) ~[classes/:?]
	at edu.ie3.simona.model.grid.GridModel$$anonfun$2.applyOrElse(GridModel.scala:409) ~[classes/:?]
	at edu.ie3.simona.model.grid.GridModel$$anonfun$2.applyOrElse(GridModel.scala:399) ~[classes/:?]
	at scala.collection.Iterator$$anon$7.hasNext(Iterator.scala:496) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.Growable.addAll(Growable.scala:61) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.Growable.addAll$(Growable.scala:59) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.ArrayBuffer.addAll(ArrayBuffer.scala:148) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.ArrayBuffer.addAll(ArrayBuffer.scala:41) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.ArrayBuffer$.from(ArrayBuffer.scala:267) ~[scala-library-2.13.0.jar:?]
	at scala.collection.mutable.ArrayBuffer$.from(ArrayBuffer.scala:255) ~[scala-library-2.13.0.jar:?]
	at scala.collection.IterableOps.collect(Iterable.scala:663) ~[scala-library-2.13.0.jar:?]
	at scala.collection.IterableOps.collect$(Iterable.scala:662) ~[scala-library-2.13.0.jar:?]
	at scala.collection.AbstractIterable.collect(Iterable.scala:904) ~[scala-library-2.13.0.jar:?]
	at edu.ie3.simona.model.grid.GridModel$.buildAndValidate(GridModel.scala:399) ~[classes/:?]
	at edu.ie3.simona.model.grid.GridModel$.apply(GridModel.scala:62) ~[classes/:?]
	at edu.ie3.simona.agent.grid.GridAgent$$anonfun$2.applyOrElse(GridAgent.scala:226) ~[classes/:?]
	at edu.ie3.simona.agent.grid.GridAgent$$anonfun$2.applyOrElse(GridAgent.scala:167) ~[classes/:?]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:37) ~[scala-library-2.13.0.jar:?]
	at akka.actor.FSM.processEvent(FSM.scala:801) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.FSM.processEvent$(FSM.scala:798) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at edu.ie3.simona.agent.grid.GridAgent.akka$actor$LoggingFSM$$super$processEvent(GridAgent.scala:109) ~[classes/:?]
	at akka.actor.LoggingFSM.processEvent(FSM.scala:941) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:923) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at edu.ie3.simona.agent.grid.GridAgent.processEvent(GridAgent.scala:109) ~[classes/:?]
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:795) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:790) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.Actor.aroundReceive(Actor.scala:532) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.Actor.aroundReceive$(Actor.scala:530) ~[akka-actor_2.13-2.6.0.jar:2.6.0]
	at edu.ie3.simona.agent.grid.GridAgent.aroundReceive(GridAgent.scala:109) ~[classes/:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.actor.ActorCell.invoke(ActorCell.scala:543) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.dispatch.Mailbox.run(Mailbox.scala:230) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242) [akka-actor_2.13-2.6.0.jar:2.6.0]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
```

**Comment by keilw** [comment] 2020-04-21 17:46
Hi, 
This is really very exotic, I don't use any of the Scala or Akka stack myself, so were you able to demonstrate the problem in a standalone Java app or JUnit test as well? I know with concurrency this can be a little challenging. 
We rarely make major updates to uom-se now, because it is in maintenance. Two bugs could be fixed if we release 1.0.11, but there is no strict deadline. I'm not sure, if you also have a chance to use Indriya, the new RI which also exist for JSR 363 btw (1.x)?

**Comment by andi-huber** [comment] 2020-04-21 18:38
This issue definitely sounds worth investigating also with Indriya. Might hit us there as well and might not be related to Scala/Akka at all. I hope I can find some time for a closer look within the next days.

**Comment by johanneshiry** [comment] 2020-04-21 19:40
Thanks @keilw and @andi-huber for the fast reply.

@keilw I know that without a sample project it is quite hard to debug this. I can try to somehow setup a very basic implementation of a java/scala project that reproduces the issue. I'll keep you updated if I can get it to this point somehow. 
I'm not familiar with Indriya, but had a fast look at it today. Is there anything we need to take care of when we switch over or can the existing code (except of the imports) be re-used? As pointed out in my initial post, we extensively use this implementation and it would cause some effort to change everything. But if it helps and is worth it, we might consider this.

@andi-huber if I can support you with additional information pls let me know.

**Comment by andi-huber** [comment] 2020-04-21 20:11
I see multiple calculation steps in your scenario that I in theory could run on different threads or even in the context of different classloaders
1) setup the Unit for [quantityA] = OHM_PER_KILOMETRE
2) setup the Unit for [quantityB] = KILOMETRE
3) setup the Quantity quantityA
4) setup the Quantity quantityB
5) quantityA.multiply(quantityB).asType(classOf[ElectricResistance])

Can you give me a hint on how you do this steps within your environment? Meaning how are these steps split up among threads or systems?

**Comment by keilw** [comment] 2020-04-21 20:14
Thanks for offering to help. Not sure, how much time he has, but hope we may also get @desruisseaux to have a look at it if he can.
He made use of `AtomicReference` in the `ServiceProvider`, and I also saw a use of `ConcurrentModificationException` in the Seshat implementation (feel free to explore that btw, if you can, I don't know every corner of it, but give it a try to see, where it does things differently)

Some API elements like `UnitFormat` explicitly state, that implementations may restrict calling methods like `label()` by multiple threads, both uom-se and Indriya probably deal with concurrent labelling a little less sophisticated.

**Comment by andi-huber** [comment] 2020-04-21 20:22
I made a first simple attempt with Indriya in trying to stresstest our given scenario, but I cannot see any issues yet. Might be setup too simple.

```java
package tech.units.indriya.unit;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.Random;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import javax.measure.Unit;
import javax.measure.quantity.ElectricResistance;
import javax.measure.quantity.Length;

import org.junit.jupiter.api.Test;

import tech.units.indriya.ComparableQuantity;
import tech.units.indriya.function.RationalNumber;
import tech.units.indriya.quantity.Quantities;

public class UnitDimensionStressTest {
    
    @Test
    public void ofReturnsNullForNull() throws InterruptedException, ExecutionException {
    
        final Random rnd = new Random();
        
        final ExecutorService worker1 = Executors.newFixedThreadPool(4);
        final ExecutorService worker2 = Executors.newFixedThreadPool(4);
        
        worker1.submit(UnitDimensionStressTest::quantityA);
        worker2.submit(UnitDimensionStressTest::quantityB);
        
        for(int i=0; i<100000; ++i) {
            ComparableQuantity<?> quantityA = worker1.submit(UnitDimensionStressTest::quantityA).get();
            ComparableQuantity<?> quantityB = worker2.submit(UnitDimensionStressTest::quantityB).get();
            
            ComparableQuantity<ElectricResistance> someOhm = 
                    quantityA.multiply(rnd.nextDouble()).multiply(quantityB).asType(ElectricResistance.class);
            
            assertNotNull(someOhm);    
        }
        
    }
    
    private static ComparableQuantity<?> quantityA() {
        final Unit<Length> KILOMETRE = 
                Units.METRE.multiply(RationalNumber.ofInteger(1000L));
        final ProductUnit<?> OHM_PER_KILOMETRE = 
                (ProductUnit<?>) ProductUnit.ofQuotient(Units.OHM, KILOMETRE);
        return Quantities.getQuantity(2L, OHM_PER_KILOMETRE);
    }
    
    private static ComparableQuantity<?> quantityB() {
        final Unit<Length> KILOMETRE = 
                Units.METRE.multiply(RationalNumber.ofInteger(1000L));
        return Quantities.getQuantity(2L, KILOMETRE);
    }
    
}
```

**Comment by johanneshiry** [comment] 2020-04-22 07:17
Hi again,

I just pushed a sample project that reproduces the issue.
You can find it here: https://github.com/johanneshiry/uom-se-issue-210

The project has two subfolders with src code with java and scala code which is very close to the structure we have in our project. The java code includes a reduced implementation of our Unit implementations (which is actually also OpenSource and can be found here: https://github.com/ie3-institute/PowerSystemUtils/tree/master/src/main/java/edu/ie3/util/quantities). 

In `com.github.johanneshiry.uomseissue210.main` you can find the Main class that can be executed. 
Inside this main class, there are two parameters that can be varried: 

- `noOfDummyDataPerActor` --> amount dummy data that is passed in for processing
- `noOfActors` --> number of actors that process the data concurrently 

It turned out that I had to vary these two parameters to reveal the error. The current configuration works on my machine and produces the exceptions we want to see. 

I tried to document the code as much as possible to make it understandable at a first glimpse. It _should_ work out of the box (tested with IDEA IntelliJ) as I used gradle as the build tool. You only have to set your Java Version to 11 in IntellIJ if you don't use Java 11 already. Pls let me know if you have any questions or if something does not work. 

Some remarks on my findings during sample project creation so far: 

- Most of the time, I could made the error visible with adapting the `noOfDummyDataPerActor` with values between 1000 and 10000 (where 5000, 7000 and 8000 have been good catches to reveal the error).

- It turned out that I have to play with the config params `noOfActors` and `noOfDummyDataPerActor` and the error messages differ slightly in the sense of that they are all thrown from the same place `AbstractUnit:260` but with different exception messages:

- `java.lang.ClassCastException: The unit: one is not compatible with quantities of type interface javax.measure.quantity.ElectricResistance`
- 
- `java.lang.ClassCastException: The unit: Ω·Ω is not compatible with quantities of type interface javax.measure.quantity.ElectricResistance`
- 
- `java.lang.ClassCastException: The unit: Ω·Ω·km is not compatible with quantities of type interface javax.measure.quantity.ElectricResistance`

- The root of the exceptions is (as expected) always between line 24 - 27 in `SimpleActor`. The interesting part is, that in contrast to my observations in our code the resulting exceptions now seem to cover the casting of totally different units that are passed in. Even if I observed the `one is not compatible` issue in our code as well, most of the time I had the exceptions shown in my first post, where the exception message unit information has been close or equal what I actually wanted to cast via `asType()`. 

I think this supports my assumption that somehow the collection of the dimensions inside of the units is not carried out in non-deterministic way. 

I hope the small project helps tracing down the error a little bit. 

If there is anything else I can do pls let me know

**Comment by johanneshiry** [comment] 2020-04-22 07:24
>  I see multiple calculation steps in your scenario that I in theory could run on different threads or even in the context of different classloaders
> 
> - setup the Unit for [quantityA] = OHM_PER_KILOMETRE
> - setup the Unit for [quantityB] = KILOMETRE
> - setup the Quantity quantityA
> - setup the Quantity quantityB
> - quantityA.multiply(quantityB).asType(classOf[ElectricResistance])
>
> Can you give me a hint on how you do this steps within your environment? Meaning how are these steps split up among threads or systems?

@andi-huber It is actually done very simple (as in the sample project as well):
- `setup the Unit for [quantityA] = OHM_PER_KILOMETRE` and `setup the Unit for [quantityB] = KILOMETRE` is done in a separate library which we just import in our project (https://github.com/ie3-institute/PowerSystemUtils/tree/master/src/main/java/edu/ie3/util/quantities)
- we then setup data with quantities (making use of our imported interfaces/Unit implementations) at a central place in one thread(`setup the Quantity quantityA`, `setup the Quantity quantityB`), then we distribute the data to several actors/threads and finally we execute the multiplication (`quantityA.multiply(quantityB).asType(classOf[ElectricResistance])`) inside of the actors/threads. 

--> Actually only the multiplication is done concurrently

**Comment by andi-huber** [comment] 2020-04-22 09:40
Good news in the mean time: I can reproduce the issue, given your code using Java only. (I converted your Scala code to Java).

**Comment by keilw** [comment] 2020-04-22 10:10
Great, are there any parts in the actual impl you saw problematic or is it mainly the application code that needs to avoid such race conditions?

**Comment by andi-huber** [comment] 2020-04-22 10:44
The issue I'm seeing is with
```java
package com.github.johanneshiry.uomseissue210.quantities;
...
import javax.measure.Unit;
...
public class PowerSystemUnits extends Units {
...
}
```
You either need to initialize this class before your actors do. (meaning force the static fields to be initialized before you allow concurrent threads to access them) or as an alternative, don't subclass the Units class. Eg. by using
```java
    public static class PowerSystemUnits {

        /* ==== Basic non electric units ==== */
        /** Kilometre */
        public static final Unit<Length> KILOMETRE = MetricPrefix.KILO(Units.METRE);

        /** Ohm per kilometre */
        public static final Unit<SpecificResistance> OHM_PER_KILOMETRE =
                        new ProductUnit<>(Units.OHM.divide(KILOMETRE));

        /** Siemens per kilometre */
        public static final Unit<SpecificConductance> SIEMENS_PER_KILOMETRE =
                        new ProductUnit<>(Units.SIEMENS.divide(KILOMETRE));

    }
```

**Comment by andi-huber** [comment] 2020-04-22 10:55
Elaborating on whats going on:
Initializing the `Units` class with all it static fields is currently not implemented in a thread-safe manner.  Hence any subclass of `Units` inherits this flaw. I believe this stumbling stone is also present with Indriya.

First of all @johanneshiry, can you verify that my suggesions fix things on your end? Then we might consider, at least for Indriya to mitigate this issue.

**Comment by johanneshiry** [comment] 2020-04-22 11:15
Thanks both of you for the ultra-fast replies! 

I just changed `PowerSystemUnits` to

``` 
import static tec.uom.se.unit.Units.*;

public class PowerSystemUnits {

    private PowerSystemUnits(){}

    /* ==== Basic non electric units ==== */
    /** Kilometre */
    public static final Unit<Length> KILOMETRE = MetricPrefix.KILO(METRE);

    /** Ohm per kilometre */
    public static final Unit<SpecificResistance> OHM_PER_KILOMETRE =
                    new ProductUnit<>(OHM.divide(KILOMETRE));

    /** Siemens per kilometre */
    public static final Unit<SpecificConductance> SIEMENS_PER_KILOMETRE =
                    new ProductUnit<>(SIEMENS.divide(KILOMETRE));

}
``` 

but that didn't help. 

For your first idea I tried the following: 
- called `Units.getInstance()` in `com.github.johanneshiry.uomseissue210.main.Main.main(args)` method before executing `run(...)` -> issue persist
- added static calls in `com.github.johanneshiry.uomseissue210.quantities.PowerSystemUnits` as follows 

```
    static {
        Units.getInstance();
    }

    private PowerSystemUnits() {
    }

    public static PowerSystemUnits getInstance() {
        return INSTANCE;
    }
``` 

and played with `PowerSystemUnits.getInstance()` in Main -> issue persists :-( 

So either I didn't understood your proposals or they _seem_ not to solve the issue. If you want me to push the changes to the test repo pls let me know

**Comment by keilw** [comment] 2020-04-22 12:03
We also extend `Units` in other modules like SI, so as of now I would keep that, although there is an abstract base class `AbstractSystemOfUnits` as an alternative if necessary, and we could make `Units` final, if that already helped? For the other stuff I am not that deep into concurrency either.
Unlike e.g. `ServiceProvider` which allows to replace the current instance, pretty much everything in `Units` is immutable, but you might like to have a look at Seshat and if you can try those tests with more than one implementation, also test against it, because Seshat has a much bigger static initializer block documented like: **We use here a "lazy final initialization" pattern...** so unless there are further problems between e.g. the lazy initialization of Scala or different JVM languages, we could explore something similar for Indriya. Seshat's `Units` class is final btw, but it has a more centralized approach than Indriya or uom-se where the whole SI and other systems are put into a central unit repository and it does not aim at extending these e.g. with Unicode or UCUM.

**Comment by andi-huber** [comment] 2020-04-22 13:48
I can confirm, I'm also still seeing the issue (Java only). However, what I said above regarding Units is still true and was just another issue our scenario can run into. I'm investigating further now.

**Comment by keilw** [comment] 2020-04-22 14:03
Ok thanks, if you can try Seshat, because even for his apps under Scala (the minimum version is Java 10 but that looks OK for him) @johanneshiry could use that as a drop-in replacement for uom-se under JSR 363, that's the beauty of having a standard with multiple implementations ;-)

**Comment by keilw** [comment] 2020-04-22 14:07
Although most of them were created by someone in our community, JSR 363 has 6(!) compatible implementations including the enum-impl (which is compatible on a smaller profile) I guess it's time to create something like https://jakarta.ee/compatibility/ for Unit-API as well ;-D

**Comment by keilw** [comment] 2020-04-22 14:08
Or maybe 7, I am not sure, if SIS passes the TCK, then it would even be 7.

**Comment by andi-huber** [comment] 2020-04-22 15:09
regarding `tec.uom:uom-se:1.0.10`

`tec.uom.se.unit.ProductUnit#equals(...)` and `#hashCode` are both not thread-safe! I'll see that I can provide a fix.

**Comment by keilw** [comment] 2020-04-22 15:20
Then what about `Objects.equals()` or similar helper methods used, are they thread-safe? Btw, @otaviojava made a few minor changes to uom-se only, mostly Java 8 optimization, but where it doesn't hurt Indriya, would it be possible to forward-port those? In future while offering a fix for problematic behavior as far as possible, we shall no longer do any "cosmetics" or nice to have improvements in uom-se since it is a legacy implementation.

**Comment by andi-huber** [comment] 2020-04-22 15:31
Werner, yes I'll have a look at Indriya as well, but first, my immediate question is, am I allowed to add/remove serializable fields in tec.uom.se.unit.ProductUnit, which changes its Serialization id/signature?

**Comment by andi-huber** [comment] 2020-04-22 16:11
I managed to fix it without changing the Serialization id/signature.
https://github.com/unitsofmeasurement/uom-se/commit/798418db163f79b495e1081e992e3117fa8b9d77

(Sorry I meant to open a PR, instead I pushed directly.)

**Comment by andi-huber** [comment] 2020-04-22 16:19
I think that did the trick, can no longer reproduce these issues. 
I'm gonna have a look at Indriya now.

**Comment by keilw** [comment] 2020-04-22 16:29
No worries, please for Indriya unless you pushed something already, let me merge the Toolchain updates for Jigsaw and multi-release-jar builds first and propose a PR then, otherwise we might see merge conflicts.

**Comment by andi-huber** [comment] 2020-04-22 16:50
Ok thx Werner! Indriya's tech.units.indriya.unit.ProductUnit is broken in a very similar way. 

I'll see that I can fix that as well.
Let me know when you are ready so I can open a PR.

**Comment by andi-huber** [comment] 2020-04-22 20:46
Now that I worked on a fix for Indriya I did pay more attention to detail there, than here. I'll need to backport, what I have done there, such that we preserve the canonical order of the unit dimension elements.

**Comment by andi-huber** [comment] 2020-04-22 21:20
PR (backporting from Indriya)
https://github.com/unitsofmeasurement/uom-se/pull/211

**Comment by andi-huber** [comment] 2020-04-23 05:31
I also need to mention, that with this fix, I do no longer see any concurrent modification issues with the initialization of the `Units`' static fields. In other words sub-classing `Units` seems no longer problematic.

**Comment by johanneshiry** [comment] 2020-04-23 06:28
Hi,

thanks for the fast and extensive help on this issue. 
I just checked out the current master and tried to use a self-compiled version of 1.0.11-SNAPSHOT version by calling `mvn package` but now it complains about 
```
Error:(13, 39) Class tec.uom.lib.common.function.Nameable not found - continuing with a stub.
public class PowerSystemUnits extends Units {
```
hence I currently cannot test your fixes. Did I miss something here when I compiled the current master by myself?

**Comment by andi-huber** [comment] 2020-04-23 06:34
Not sure but, I think you need to `mvn install`.

**Comment by johanneshiry** [comment] 2020-04-23 06:44
I just downloaded the master branch and tried to compile it by myself with `mvn package` but when I imported it in my sample project to see if that fixes the issue, I ended up with the following error: 

```
Error:(13, 39) Class tec.uom.lib.common.function.Nameable not found - continuing with a stub.
public class PowerSystemUnits extends Units {
``` 

Did I miss something here when I compiled it?

**Comment by johanneshiry** [comment] 2020-04-23 06:52
Didn't worked with `mvn install`, but adding the dependency for `uom-lib-common` manually did the trick. 

With the self-compiled version based on the current master I couldn't reproduce the issue anymore -> seems solving the issue over here as well. 🎉

**Comment by andi-huber** [comment] 2020-04-23 06:55
Nice! Did you test against my forked branch or the main project's one?
(I have opened a yet pending PR).

**Comment by andi-huber** [comment] 2020-04-23 06:57
(I'm waiting for Werner to approve or merge https://github.com/unitsofmeasurement/uom-se/pull/211.)

**Comment by johanneshiry** [comment] 2020-04-23 06:59
I tested against the current main master branch with the latest commit `210: thread-safety for ProductUnit#equals(...) and #hashCode - 798418db163f79b495e1081e992e3117fa8b9d77`.

In addition I used this version as base and manually applied your PR #211 on it by replacing the whole `ProductUnit.java` with your adapted version of PR #211 

Both versions are working. Is there anything else I should test?

**Comment by andi-huber** [comment] 2020-04-23 07:00
Thx, that's perfect. No more tests required.

**Comment by johanneshiry** [comment] 2020-04-23 07:01
Thanks a lot for you efforts and your help! 

Do you know if there will be a fixed release of this soon - maybe even for Indriya? Then we might consider to take this as a chance to switch to Indriya as well.

**Comment by andi-huber** [comment] 2020-04-23 07:08
A fix for Indriya is also ready and pending for acceptance/merge. The release stuff is up to @keilw . (I suspect it should not take too long.)

Thanks for digging this one up and helping to get to the very bottom of it!

**Comment by keilw** [comment] 2020-04-23 08:00
I merged it thanks, the toolchain was already merged into master and we have specialized classes for Java 9, Java 12 and 14 in Indriya now ;-) Can this be closed, or is there a remaining problem?

**Comment by andi-huber** [comment] 2020-04-23 08:02
Thx @keilw ! There is also a PR peding here ...

> (I'm waiting for Werner to approve or merge #211.)

**Comment by keilw** [comment] 2020-04-23 08:04
Ok will merge, I thought it was pushed directly here.

**Closed** 2020-04-23 08:06 UTC
Labels: bug, in progress
