### ISSUE TITLE
error parsing dimensionless unit "1"

### ISSUE THREAD

**Issue by garretwilson** [unitsofmeasurement/uom-se#147] opened 2017-03-16 23:42 UTC
I'm using:

```xml
<dependency>
  <groupId>tec.uom</groupId>
  <artifactId>uom-se</artifactId>
  <version>1.0.4</version>
</dependency>
```

I had understood from JSR 363 "supported quantities" that there is a dimensionless quantity type with a unit constant `ONE` with symbol `1`. So I tried to use a `UnitFormat.parse("1")`, but I'm getting an `Invalid unit 1` error.

1. I don't understand. Does JSR 363 define a unit for dimensionless quantities with symbol `1` or not?

2. Secondly, how do I represent the absence of a unit in JSR 363? For `UnitFormat.parse()`, JSR 363 says, "If there is no unit to parse, a dimensionless unitary unit is returned." But "no unit to parse" is ambiguous; does that mean the empty string `""`, or `null`? (The API Javadocs for that method don't clear up the matter any, and don't even mention whether `null` is allowed.)

**Comment by garretwilson** [comment] 2017-03-16 23:53
I tried `UnitFormat.parse(null)`, but that gave me a `NullPointerException`. But it worked with `UnitFormat.parse("")`. But this doesn't really make sense --- there is no unit representation listed in JSR 363 with the representation `""`. The more semantic argument would have been `null`, which indicates that there is no representation (unlike `""`, which indicates that there is a representation of the empty string.)

When I use `unitFormat.format(unitFormat.parse(""))` to get a string back for this "missing" unit, it serializes as `"one"`. This confuses me; JSR 363 clearly says that the "symbol" should be `1`. So this is all confusing me: `""`, `"ONE"`, and `"1"`. Which is correct? (JSR 363 seems pretty clear that it should be `"1"`. Maybe I'm misreading it.)

**Comment by garretwilson** [comment] 2017-03-17 00:01
Lastly where is the `Unit` constant `ONE` defined? (I would hope it would be part of the JSR 363 dependency, and not any implementation.)

Note that the comments in `tec.uom.se.AbstractUnit` make reference to:

```java
//... Units.ONE ...
```

Yet `ONE` doesn't seem to be defined in `tec.uom.se.unit.Units` or any of its base classes. (There is a `ONE` defined in `AbstractUnit`. Is that the right `ONE`? Why isn't it defined alongside the other units in `Units`, or better yet, in a JSR 363 class?)

The dimensionless unit has me very confused.

**Comment by keilw** [comment] 2017-03-17 00:26
The visual representation of `ONE` is actually "one".  There is no alias like "1" but we really have to check whether or not it might clash with operations involving numbers. `AbstractUnit.ONE` is a special constant similar to `BigDecimal.ONE`. That is why it's declared at least on an abstract base class (as opposed to `BigDecimal `or `Long`) and not e.g. in the `Units ` collection. It is a special constant that is independent of particular unit systems. We considered declaring it there, but it led to problems with static initialization of certain classes, so it went to where most similar constants are also declared. "JSR 363 class" I suppose you mean the interface like `Unit`? That prior to Java SE 8 won't work and the API is backward compatible with at least Java SE 7 (you may recompile it in SE 6, too if you need) and Java ME 8. 
The constant needs concrete behavior, it is a `ProductUnit ` from the implementation, so that won't work on the API level. Potentially using `default ` methods a pure Java SE 8 interface could allow it, but Unit-API 1.0 guarantees Java SE 7 or ME 8 backward compatibility. Maybe in a future version we could explore moving such a constant into the API but it is unlikely before a whole new JSR based on different versions of the platform or no longer meant to run on Java ME if that was phased out some day.

`Units `references `ONE `as a `Dimensionless `default unit. so` getUnit(Dimensionless.class)` will return it for consistency. I can see, if an alias of "1" works for `ONE `without negative side-effects.

**Comment by garretwilson** [comment] 2017-03-17 00:50
> Unitsreferences `ONE`as a `Dimensionless`default unit. so`getUnit(Dimensionless.class)` will return it for consistency. I can see, if an alias of "1" works for `ONE`without negative side-effects.

I'm only trying to understand the spec, and as far as I can tell, there is a table showing `"1"` for the "symbol" for the `ONE` constant. Am I reading that wrong? And if that's the symbol, shouldn't `UnitFormat.parse()` be able to parse the symbol?

There's no point in supporting `"1"` in your implementation if that's not what the spec says. (And there's no point in having multiple aliases for `ONE`, as that would defeat the purpose of standardization.) On the other hand, if the spec _does_ say that the symbol is `"1"`, then all implementations _must_ parse it as the `ONE` constant, isn't that right?

So first we need to be clear what the spec says. I'm not trying to bend your implementation contrary to the spec.

Maybe the specification could be clearer on this point. I guess what confuses me is a column named "symbol" and a value shown as "1" in JSR 363.

**Comment by keilw** [comment] 2017-03-17 01:05
We cannot support "1" in this case, it interferes with parsing in so many areas because it is not the same as the number 1 e.g. `BigDecimal.ONE`.
https://www.av8n.com/physics/dimensionless-units.htm probably highlights this best, the `ONE `in this case stands for Units of Dimension `ONE `aka `Dimensionless ` units.  We'll look for ways to explain that in more detail. Since it is on an implementation level, unlike the Dimensionless quantity itself, there should be no impact on the API or Spec, but e.g. the RI guide (as of now there is no variation for Java SE, but the more uom-se evolves, the more likely it is we'll probably create a separate tutorial for Java SE like it, too.

This in `AbstractUnitFormat `explains exactly, why you get the default Dimensionless unit for an empty string
```
Parses a portion of the specified <code>CharSequence</code> from the specified position to produce a unit. If there is no unit to parse
   * {@link AbstractUnit#ONE} is returned.
```

I will close this here, please create a ticket here https://github.com/unitsofmeasurement/unit-ri-userguide if you can. It will be the basis for any additional user guide and the behavior you see here is identical in the RI anyway. Any change or introduction of new or different constants or different behavior must be exactly the same here as it is in the RI at least for the basic elements like `SimpleUnitFormat`.

**Closed by keilw** 2017-03-17 01:05 UTC

**Comment by keilw** [comment] 2017-03-17 01:19
Actually the RI (because it's an official deliverable of the JSR there can be areas documented a little further, uom-se is currently not an official part of the JSR) there's this reference in the ONE constant: https://en.wikipedia.org/wiki/Natural_units#Choosing_constants_to_normalize Maybe that helps, I will also add it to the SE class.

**Comment by garretwilson** [comment] 2017-03-17 13:37
Could clarify something for me? How do I know if a particular quantity is dimensionless --- _using only JSR 363_?

The point of JSR 363 is to program to a general API and not be tied to some implementation. I therefore don't want to compare a quantity's unit to `AbstractUnit.ONE`, as that ties my code to the `uom-se` implementation. Because "dimensionless quanities" is part of the specification, I would expect I could ask "is this quantity dimensionless?" using solely JSR 363 in a way that would work across implementations. Is there a JSR 363 API call I can make to determine if the quantity is dimensionless?

**Comment by keilw** [comment] 2017-03-17 14:06
I'm afraid there are no ways to use the `Dimensionless` quantity or type directly.
`AbstractUnit.ONE` is a manifestation of `Dimensionless`, the name has already been given ages ago. It existed in JSR 275 (there `Unit` was a class, so we could put it there, but 275 and JScience has a coupling between API and RI that were too tight in many cases, part of the reason it was rejected)

https://java.net/projects/jscience/sources/svn/content/trunk/jscience/physics/src/main/java/org/jscience/physics/unit/formats/LocalUnitFormat.java?rev=696 in JScience returns this constant it declared in 
https://java.net/projects/jscience/sources/svn/content/trunk/jscience/physics/src/main/java/org/jscience/physics/unit/SI.java?rev=696, but again, the number of implementations and extensions were limited, so having `AbstractUnit.ONE` means, you can use the abstract base class but it does not need a particular unit system for that constant. The current  Java type system makes it hard at runtime in most cases to know the quantity type, see https://en.wikipedia.org/wiki/Comparison_of_C_Sharp_and_Java#Type_erasure_versus_reified_generics. C# or F# in the .NET platform have some advantages over Java as people like Andrew Kennedy (see the spec for references to his work on unit support in programming languages) also confirmed when we discussed this JSR and the previous ones.

**Comment by garretwilson** [comment] 2017-03-17 14:20
I'm not sure if you're understanding the question. Let me bring it into real life.

Let's say that my RESTful layer loads a `Quantity` from the the database. At this point I'm using JSR 363, and my code is completely implementation-agnostic. I could switch JSR 363 implementations at any time. That, after all, is the whole point of having JSR 363.

So I want to serialize my quantity to JSON to send back to a RESTful client. I get a `UnitFormat` --- again note that I am doing this completely in JSR 363, agnostic to any implementation:

```java
UnitFormat unitFormat = ServiceProvider.current().getUnitFormatService().getUnitFormat();
```

Now I want to create a JSON quantity in the form `{"value":123.4, "unit":"mL"}`. The first part is easy:

```java
writer.write("{\"value\":" + quantity.getValue());
```

Now I want to write the unit. But if this quantity has no dimensions, I just want to leave off the unit. (After all, the RESTful API is for many users, some of whom will get confused if I start sending a unit string of `"one"` back.)

So... how can I tell if the unit is dimensionless? _I can't use `AbstractUnit.ONE`_, because that will tie me `uom-se`, defeating the purpose of JSR 363. (If I'm tied to `uom-se`, why have JSR-363 in the first place? We could have just finished JScience and been done with it years ago, if we're going to be tied to an implementation.)

* Can I say `if(!"".equals(quantity.getUnit().getSymbol))`? Does JSR 363 guarantee that the symbol of the dimensionless unit will always be `""`, and that no other unit will have a symbol of `""`?
* Can I say `if(!unitFormat(quanity.getUnit()).equals("one"))`? Does JSR 363 guarantee that `UnitFormat` (of all implementations) will format the dimensionless unit as `"one"`, and that no other units will serialized as `"one"`?

**Comment by keilw** [comment] 2017-03-17 15:03
Actually most of the REST use case was done already: https://github.com/unitsofmeasurement/jackson-module-unitsofmeasure It is an improved fork of https://github.com/jeffkole/jackson-module-unitsofmeasure created by a (former) employee of Opower, the energy service provider. Who took JScience 5 and "finished" it for his purpose, it's even in the repo in binary form. It is safe to assume, Opower either used it before or still does even in production. You always need some implementation of a JSR. Whether it is Weld or Open WebBeans, the CDI API on its own is worthless even if it may offer some annotations in the API level. Similar with others like Bean Validation. There some constraints are very general (like `Number`, `Date`, etc.) so they are in the javax package space (like Dimensionless or a few base quantities are in 363) while extensions (like Polish Social Security Number) are in the RI, Hibernate Validator. It is similar in this case. You cannot use the API by itself. JSR 275 (JScience 4) may have been misleading to many people because it was a monolithic combination of API and RI (a bit like java.time for JSR 310 ;-) but except maybe that case or a few other JSRs inside the JDK itself, they are always separate. And interchangeable. Your code can use the RI or Uom-SE, with little or no modification, but for certain comparisons you must use the implementation or implement something yourself similar to https://github.com/unitsofmeasurement/uom-impl-enum. It declares `ONE` in https://github.com/unitsofmeasurement/uom-impl-enum/blob/master/src/main/java/tec/uom/impl/enums/unit/DimensionlessUnit.java because it's based on enums. There is no way (at least till Java SE 8+ where the default methods of an interface could allow a constant to be based on that) without a bit of imlementation to do this constant. It can't just say Unit<Dimensionless>. Using reflection might work but it is a no-go for Java ME so we did not use it (except in a few places in uom-se as an alternate approach to `QuantityFactory`). There is only one `Dimensionless` quantity (although nobody is prevented from creating MyDimensionless using the same mechanism, but they would not be identical, both extending `Quantity` at most) but there can be dozens or hundreds of `Dimensionless` units. `ONE` is just a default constant. And `AbstractFormat` in either the RI or the SE implementation by convention return this constant to avoid a `null` value.  Only the SE 8 implementation had something like `Optional` and that mostly for reasons I mentioned earlier (no reified generics in Java so far) has major problems when combined with multiple levels of generics (something like `Optional<Unit<?>>` or even deeper) The JSR won't mandate a particular constant to return. If you're aware of the consequences, a UnitFormat implementation could just as well return `null` instead of `AbstractUnit.ONE` or `DimensionlessUnit.ONE`.

**Comment by garretwilson** [comment] 2017-03-17 15:21
As always, @keilw , I appreciate your responses, and also that you don't get irritated at my questions. 😄 I found your answer hidden inside the response:

> You cannot use the API by itself.

I've thought about this a bit more, and I'm not so sure. The API guarantees that `UnitFormat.parse("")` will return a dimensionless unit. Quoting JSR 363: "If there is no unit to parse, a dimensionless unitary unit is returned." So wouldn't the following be an implementation-agnostic way to check for a quantity with no units?

```java
UnitFormat unitFormat = ServiceProvider.current().getUnitFormatService().getUnitFormat();
Unit<?> NO_UNIT = unitFormat.parse("");
if(myQuantity.getUnit().equals(NO_UNIT)) {
  //TODO don't include unit in JSON, for example
}
```

Wouldn't that be an implementation-agnostic approach for testing a dimensionless quantity? Why wouldn't that work?

**Comment by garretwilson** [comment] 2017-03-17 15:28
> You cannot use the API by itself.

I understand I cannot use the API without an implementation; that's fundamental. Also fundamental is that _the application should be programmed to the API, not the implementation_, and that's what I'm trying to do. We don't want to have dependencies to the implementation within the code --- even though yes I understand that my Maven POM (for example) must reference some implementation in the final application.

**Comment by keilw** [comment] 2017-03-17 15:34
I hope to migrate https://github.com/unitsofmeasurement/jackson-module-unitsofmeasure to JSON-B 1.0 when that goes final, but for now I plan to use the latest ucum-system 0.7 (SNAPSHOT)

**Comment by keilw** [comment] 2017-03-17 16:33
We did have this JIRA item once in JSR 363: https://java.net/jira/browse/UNITSOFMEASUREMENT-77 At a very early stage (and it was explored in JSR 275) we hoped, that an operation like `Length * Length ` could produce `Area` directly, but it turned out that was not possible, so it ended up being `Quantity<Length>.multiply(Quantity<Length>) = Quantity<?> `and asType() allows to further deal with it as `Quantity<Area>`.  I know it may not be perfect, but the Java type system has certain limitations so based on what was introduced with Generics first in JSR 275 this is the best compromise between even compile-time type safety for many operations and a dynamic, extensible type system. ICU4J/Unicode knows something like a "subtype" on the unit which is essentially "length", "area", etc. as a string. OSGi Measurement and other non-generic solutions all have similar attributes, but they will only work at runtime and throw runtime errors even for basic operations like "`Unit<Length> + Unit<Mass>`" or trying to convert `METRE` into `KILOGRAM`.

**Comment by keilw** [comment] 2017-03-17 16:37
At the moment even with reflection it's pretty much impossible to find out if a Unit you get from either `parse()` or any other operation is `Unit<Mass>` or `Unit<Dimensionless>`. If we added some runtime information like ICU4J does, we could do additional runtime checks. It could be an extension in future if we feel it makes sense. Other possible approaches but they all won't work at runtime are JSR 308 Type annotations. Even Andrew Kennedy's F# Measure framework has some elements that are typesafe at compile-time but you lose the information during runtime.

**Comment by keilw** [comment] 2017-03-17 21:24
Please see https://github.com/unitsofmeasurement/uom-systems/issues/64 related to parsing and the reopened https://github.com/unitsofmeasurement/uom-systems/issues/21 related to formatting. Actually neither of these formats are mathematically wrong, but they are unusual or wrong based on the UCUM print variant.

**Comment by garretwilson** [comment] 2018-09-10 17:05
@keilw , was this fixed in the new JSR? In there some standard dimensionless representation, or do we have to depend on some implementation?

In other words, with the new JSR we now round-trip serialization of any quanty's unit? Right now (as discussed above), I have to make sure I create a dimensionless quantity using `""` as the input, but before I serialize it I have to change this special `ONE` value back to `""`, and when I use `ONE`, I have to use some specific implementation, which breaks the principle of "program to interfaces".

So I hope in the new JSR you either:
* Promoted the `ONE` constant to the actual JSR API, or
* Dispensed with the `ONE` constant altogether and used some common representation for dimensionless quantities, such as `"1"` or `""`.

**Comment by keilw** [comment] 2018-09-10 17:19
I'm afraid this is not so easy.

While we "promoted" not only the `Prefix` interface to the API but found a way to define most implementations like `BinaryPrefix` or `MetricPrefix` to the API as well (with their constant definitions of each prefix) `ONE` is implementation specific. Just like `BigDecimal.ONE` the closest equivalent in the JDK itself. Therefore the JDK does not define and never likely will do something like `Number.ONE` on the abstract (quasi API) base class level either. `BigDecimal` is a concrete implementation. And so is what backs the `ONE` constant in the JSR. The new RI is largely based on uom-se although it has progressed quit a bit lately. I believe there is a ticket somewhere and we could try as hard as possible to add e.g. some kind of aliasing, but whenever you just used `"1"` in its place, parsing becomes extremely problematic if you ended up with something like `1x1` etc. Which one would be `ONE` and which one the plain literal number 1 in this case?

**Comment by garretwilson** [comment] 2018-09-10 17:31
But there is still the problem with this proprietary `ONE` unit that isn't part of the API, but should be.

When I call `Quantity.getUnit()`, before I even format it, I need to know if it is "the unit that represents a dimensionless quantity". This could be done in several ways:

* You could return an `Optional<Unit<Q>>`, so that if it returns `Optional.empty()`, I know it is a dimensionless quanity.
* You could return `null` if it is a dimensionless quantity.
* If it is a dimensionless quantity you could return a special value _in the API_ such as `Unit.ONE`.
* Heck, you could even add a `Unit.isDimensionless()` method!

Instead, I'm forced to compare the unit to "some specific implementation of the JSR", which means my library is no longer written to the JSR interface but has to have special knowledge of whatever implementation I'm using.

Right now for example I have to use code like this to determine whether something is dimensionless:

```java
if(tec.uom.se.AbstractUnit.ONE.equals(quantity.getUnit())) {
  …
}
```

My code should not be required to have any knowledge of `tec.uom.se.AbstractUnit`, which is some specific implementation of the JSR API. This breaks the whole purpose of programming to an API.

**Comment by keilw** [comment] 2018-09-11 11:34
Since Java 8 and above allow not only static constants on an Interface but e.g. a default method, maybe there could be a solution. Those of you who signed the ECA please if you have a more concrete approach, file a PR. Better for Indriya, but if uom-se for the time being is what you are using, then it's also fine there (we would port it, since both require Java 8 or above)

**Comment by keilw** [comment] 2018-09-11 13:20
The Seshat implementation derived from SIS got a constant called `UNITY` in [Units](
https://github.com/unitsofmeasurement/seshat/blob/master/src/main/java/tech/uom/seshat/Units.java) Essentially it does a very similar thing as the `ONE` constant in uom-se or indriya, a main reason why putting `ONE` into the API seems wrong because it would force implementations that handle it differently to use it if they don't want to. A prefix like `MILLI` or `MICRO` is pretty obvious and we standardized that by making it pluggable, so each implementation has to "inject" its own UnitConverter to make it work. Unless others including @desruisseaux feel, we should put a constant like `ONE` or `UNITY` into the API, it's better to keep it implementation-specific, but maybe calling it differently there solves issues like parsing "1" in certain situations. The way it's treated is similar, but Seshat gave it an alias of "1". I mentioned we consider something similar to overcome the mentioned problems.

**Comment by keilw** [comment] 2018-09-11 14:27
What about other Dimensionless units like PERCENT or (in some implementations) different units like BEL, DECIBEL, etc.?

**Comment by desruisseaux** [comment] 2018-09-11 17:37
The case of percent is already noted as a comment. Since it is a conventional unit with a scale of 100, `Units.PERCENT.getSystemUnit() != Units.PERCENT`.

The case of other dimensionless units like `Angle` or `Salinity` is catch by the `myUnit.asType(Dimensionless.class)`. It is the reason why above snippet use try-catch instead of the more efficient `myUnit.getBaseUnits() == null` (more efficient but does not differentiate dimensionless units).

I don't think that the API should provide a `ONE` or `UNITY` constant since it would force the definition of a `Unit` implementation in the API. But the API may define a minimal set of symbols that `UnitFormat` shall support however, and that minimal set could include the `1` symbol.

**Comment by keilw** [comment] 2018-09-11 19:56
I think so, too, but more than happy to use some of the experience by Seshat even renaming it to UNITY or some kind of alias.

**Comment by desruisseaux** [comment] 2018-09-11 20:00
I have no strong opinion on the constant name; we can leave it to each implementation. What matter more is the symbol, if we choose to publish a list of mandatory symbols.

**Comment by keilw** [comment] 2018-09-11 20:29
I know in the early days a `SymbolMap` was even an abstract API element, but now it's part of some implementations like Indriya or before (not the 1.0 RI because it relies on `ResourceBundle` or `Locale`)

**Comment by keilw** [comment] 2018-09-12 12:37
What all 3 `UnitFormat` implementations have in common (beside the fact, that Seshat calls a concrete class like that, too which is a little ambiguous and can be tricky) is they are based on expression parsing and backed by ResourceBundles. That makes it a bit harder than `SimpleUnitFormat` (with all its drawbacks in that respect) to extend it. Seshat has the notion of a Registry (somewhat closer to UCAR's UnitDB) so more than one unit system could be added at runtime, but what about formatting needs, if say all the various unit names and aliases have to be registered and added, too? Most of this goes beyond the discussion here, so let's try to keep it in the issue trackers of these repositories.
