### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by inesgradischnig** [unitsofmeasurement/uom-se#135] opened 2017-01-13 16:00 UTC
Hi,

I have a question/or maybe bug report for the SimpleUnitFormat (uom-se 1.0.2).

If I try to parse units that contain numbers, SimpleUnitFormat 'sometimes' produces an Exception. It seems that some constellations work and some not.

**For example**
I try to parse '1/s' (=Hertz) and get a ParserException.
I try to parse 'mg/100·g' this works fine.
I try to parse  'mg/25·g' this works fine.
I try to parse  '100·g/mg' this throws an Exception.

Is there a difference if the number is in the dividend or divisor ?
Is there a possibility to omit the '·' in 'mg/25·g' and just write 'mg/25g' instead ?

**My SourceCode looks like**
UnitFormat format = ServiceProvider.current().getUnitFormatService().getUnitFormat();
format.parse("1/s");

**The Exception is**
		javax.measure.format.ParserException: Parse Error
		at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parseProductUnit(SimpleUnitFormat.java:502)
		
Thanks for the answer

**Comment by keilw** [comment] 2017-01-13 19:27
Did you try 1.0.3-SNAPSHOT, too? Will try to reproduce them. And see, which ones we can address in 1.0.3.

**Comment by inesgradischnig** [comment] 2017-01-14 08:29
Hi Werner, we have version 1.0.2, i did not try 1.0.3-SNAPSHOT.

**Comment by keilw** [comment] 2017-01-14 21:21
Please try if you can. You'll find the additional repositories in the POM https://github.com/unitsofmeasurement/uom-se/blob/master/pom.xml

**Comment by inesgradischnig** [comment] 2017-01-14 23:08
I tried id with 1.0.3-SNAPSHOT it doesn't work here too. The detail message of the ParseException is: 'unexpected token 8'.

**Comment by inesgradischnig** [comment] 2017-01-14 23:45
I found another parsing problem. 
If I output the unit of a calculation, the toString method tells me, that the unit is 'kg/2.5E7·g' this is correct.
But if I try to parse 'kg/2.5E7·g' then a ParseException is thrown with 'unexpected token 1'.

**Comment by keilw** [comment] 2017-01-15 13:19
Could you provide code saples for the result that has a string representation of  'kg/2.5E7·g' please?
Not every result of an operation must be parseable. Especially 'kg/2.5E7·g' sounds like there is no `label()` for this result, therefore parsing is usually not possible either.

**Comment by inesgradischnig** [comment] 2017-01-15 17:18
Sorry, I made a mistake, the unit string is 'kg/2.5E7/g'.

The use case is, that I have to read (=parse) and write normalized values e.g. we measure a parameter in mg and normalize it to 25g bodyweight.

The unit of the normalized value should look like 'mg/(25*g)' or even better 'mg/25g'. We use 'mg/25/g' because parentheses in units cannot be parsed (ParseException ‘unexpected token 2’). And it is not possible to define a label or alias for 25g, because valid lables cannot start with a digit. 

The sample quantity is:

UnitFormat format = ServiceProvider.current().getUnitFormatService().getUnitFormat();
Quantity mg_per_25g_Bodyweight = Quantities.getQuantity(new BigDecimal("1"), format.parse("mg/25/g"));

mg_per_25g_Bodyweight.toString() ... the output is **1 kg/2.5E7/g**

**Comment by keilw** [comment] 2017-01-15 23:31
Thanks for the code snippet. I created a small demo app under "health-se" (because it seems very close to e.g. the BMI demo there) https://github.com/unitsofmeasurement/uom-demos/blob/master/domain/health-se/src/main/java/tec/uom/demo/health/se/BodyWeightDemo.java

You cannot have a label start with a digit but any other label would work, I called it "bw25g" for test purposes. Not with `UnitFormat` on an API level right now, but using e.g.  `SimpleUnitFormat` you could also use `alias()`. It does not affect the output with `toString()` but adds further strings for parsing. 

Does that help for now? Based on requirements like https://github.com/unitsofmeasurement/uom-se/issues/134 it would be great to have 1.0.3 out relatively soon.

**Comment by inesgradischnig** [comment] 2017-01-16 08:05
We have a lot of normalizations, not only bodyweight (different dimensions). And the unit string, that has to be reported finally is entered by the user. I think it is no problem for the user to enter mg/bw25g ... but ... the user will be able to normalize per 25g or 100g etc. So we have to provide labels for all possibilities for all dimensions. But the label solution is a good workaround for now.

The showstopper for our project is, that we cannot parse parameter we read from measurement files.
The common thing of these parameter is, that they contain an integer value in the dividend or divisor.
Samples:
1/s
10E6/ml
10E3/µl
They all throw ParseExceptions.

**Comment by amalic** [comment] 2017-01-16 12:50
Hi, I have the same issue when parsing units starting with a numeric character. Any news on that?

**Comment by keilw** [comment] 2017-01-16 23:09
The label may not start with a number or certain other special characters including +, -, * or other operators. To ensure, there is no confusion between where the unit starts and operators between them or when you parse a quantity.

Imagine you have a unit like "2Eggs" and instantiate a quantity like `Quantities.getQuantity(2, 2EGGS)` the string representation of the quantity may look like 22Eggs (normally there is a space between them based on the `QuantityFormat` in implementations like uom-se, but `UnitFormat` implementations cannot be sure, there is a space between the number and the unit, therefore standard implementations like  `SimpleUnitFormat` currently won't allow a digit to start a unit label or alias to avoid parsing problems. `SimpleUnitFormat` is somewhat comparable to `SimpleDateFormat` in the JDK. There are certain things you cannot do when formatting dates, e.g. use a digit as separator for a date string like "16-01-2017". Imagine you tried to parse "1600102017" if "0" was used instead of "-".  I imagine this being impossible and prevented. While not digging into the codebase, I also see it extremely hard trying to use a number as a currency code in `CurrencyUnit`. There are separate numeric currency codes, but none of the ISO codes start with a number. https://en.wikipedia.org/wiki/ISO_4217. alpha-2 or alpha-3 already suggest, those codes for country or currency must be alphabetical. As of now, we follow a similar convention for simple unit parsing.

Other unit formats like `EBNFUnitFormat` offered with uom-se are based on resource bundles or similar data, so they often won't take the `label()` or `alias()` methods into consideration. The Javadoc http://static.javadoc.io/javax.measure/unit-api/1.0/javax/measure/format/UnitFormat.html states this is implementation-specific. For sophisticated formatting and parsing needs, it could be a good idea to either use another `UnitFormat` implementation or create your own custom-specific implementation.

**Comment by inesgradischnig** [comment] 2017-01-17 08:31
Thanks for the response, I understand the reason why labels cannot start with a digit. And that it would be necessary to provide a own UnitFormat for sophisticated parsing.

But it it would be great if SimpleUnitFormat can parse units like '1/s' out of the box.

**Comment by keilw** [comment] 2017-01-17 21:57
Well it's a variation of https://java.net/jira/browse/UNITSOFMEASUREMENT-166 or https://java.net/jira/browse/UNITSOFMEASUREMENT-140 (which was about Hz being wrongly formatted 1/s in the first place, thus what you mentioned may be a side-effect of that formatting issue being addressed) We are going to move the post 1.0 issues from JIRA since java.net is going offline soon. And will track them either in the RI or (where they apply to both) in this tracker, but likely under a new number and description (with a cross reference to this maybe)

**Comment by keilw** [comment] 2017-01-19 22:09
I created https://github.com/unitsofmeasurement/uom-se/issues/136. Will close this one in preparation of 1.0.3.

**Closed by keilw** 2017-01-19 22:09 UTC
Labels: in progress
